from flask import Flask, request, jsonify, send_file, send_from_directory
from flask_cors import CORS
from werkzeug.utils import secure_filename
import os
from pathlib import Path
import tempfile
from datetime import datetime

# Import your RAG pipeline here
# from your_rag_module import generate_study_guide

app = Flask(__name__, static_folder='.')
CORS(app)  # Enable CORS for frontend-backend communication

# Configuration
UPLOAD_FOLDER = 'uploads'
OUTPUT_FOLDER = 'outputs'
ALLOWED_EXTENSIONS = {'pdf', 'docx', 'txt'}
MAX_FILE_SIZE = 16 * 1024 * 1024  # 16MB

# Create necessary folders
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['OUTPUT_FOLDER'] = OUTPUT_FOLDER
app.config['MAX_CONTENT_LENGTH'] = MAX_FILE_SIZE


def allowed_file(filename):
    """Check if file extension is allowed"""
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@app.route('/')
def serve_frontend():
    """Serve the HTML frontend"""
    return send_from_directory('.', 'index.html')


@app.route('/api/generate', methods=['POST'])
def generate_study_guide():
    """
    Main endpoint to generate study guide
    Expects:
    - file: uploaded file (PDF, DOCX, TXT)
    - query: summary query from user
    """
    try:
        # Validate request
        if 'file' not in request.files:
            return jsonify({'error': 'No file uploaded'}), 400
        
        if 'query' not in request.form:
            return jsonify({'error': 'No query provided'}), 400
        
        file = request.files['file']
        query = request.form['query']
        
        # Validate file
        if file.filename == '':
            return jsonify({'error': 'No file selected'}), 400
        
        if not allowed_file(file.filename):
            return jsonify({'error': 'Invalid file type. Only PDF, DOCX, and TXT are allowed'}), 400
        
        # Save uploaded file
        filename = secure_filename(file.filename)
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        unique_filename = f"{timestamp}_{filename}"
        file_path = os.path.join(app.config['UPLOAD_FOLDER'], unique_filename)
        file.save(file_path)
        
        print(f"File saved: {file_path}")
        print(f"Query: {query}")
        
        # TODO: Call your RAG pipeline here
        # Replace this with your actual RAG pipeline function
        # result = your_rag_pipeline(file_path, query)
        
        # PLACEHOLDER: Mock RAG processing
        output_filename = f"study_guide_{timestamp}.pdf"
        output_path = os.path.join(app.config['OUTPUT_FOLDER'], output_filename)
        
        # For now, create a mock output file
        # Replace this with actual RAG output
        mock_content = f"""
        STUDY GUIDE GENERATED BY RAG PIPELINE
        =====================================
        
        Source File: {filename}
        Query: {query}
        Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        
        This is a placeholder. Your RAG pipeline will generate the actual content here.
        """
        
        with open(output_path, 'w') as f:
            f.write(mock_content)
        
        # Return success response with download info
        return jsonify({
            'success': True,
            'message': 'Study guide generated successfully',
            'filename': output_filename,
            'download_url': f'/api/download/{output_filename}'
        }), 200
        
    except Exception as e:
        print(f"Error: {str(e)}")
        return jsonify({'error': f'Server error: {str(e)}'}), 500


@app.route('/api/download/<filename>', methods=['GET'])
def download_file(filename):
    """
    Endpoint to download generated study guide
    """
    try:
        file_path = os.path.join(app.config['OUTPUT_FOLDER'], secure_filename(filename))
        
        if not os.path.exists(file_path):
            return jsonify({'error': 'File not found'}), 404
        
        return send_file(
            file_path,
            as_attachment=True,
            download_name=filename,
            mimetype='application/pdf'
        )
        
    except Exception as e:
        print(f"Download error: {str(e)}")
        return jsonify({'error': f'Download failed: {str(e)}'}), 500


@app.route('/api/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({
        'status': 'healthy',
        'message': 'RAG Study Guide API is running'
    }), 200


# Optional: Cleanup old files periodically
@app.route('/api/cleanup', methods=['POST'])
def cleanup_old_files():
    """Clean up old uploaded and generated files"""
    try:
        import time
        current_time = time.time()
        cleanup_age = 3600  # 1 hour in seconds
        
        deleted_count = 0
        
        # Clean uploads folder
        for filename in os.listdir(app.config['UPLOAD_FOLDER']):
            file_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
            if os.path.isfile(file_path):
                if current_time - os.path.getmtime(file_path) > cleanup_age:
                    os.remove(file_path)
                    deleted_count += 1
        
        # Clean outputs folder
        for filename in os.listdir(app.config['OUTPUT_FOLDER']):
            file_path = os.path.join(app.config['OUTPUT_FOLDER'], filename)
            if os.path.isfile(file_path):
                if current_time - os.path.getmtime(file_path) > cleanup_age:
                    os.remove(file_path)
                    deleted_count += 1
        
        return jsonify({
            'success': True,
            'message': f'Cleaned up {deleted_count} old files'
        }), 200
        
    except Exception as e:
        return jsonify({'error': f'Cleanup failed: {str(e)}'}), 500


if __name__ == '__main__':
    print("=" * 50)
    print("RAG STUDY GUIDE BACKEND STARTING...")
    print("=" * 50)
    print(f"Upload folder: {os.path.abspath(UPLOAD_FOLDER)}")
    print(f"Output folder: {os.path.abspath(OUTPUT_FOLDER)}")
    print("Frontend will be available at: http://localhost:5000")
    print("=" * 50)
    
    app.run(debug=True, host='0.0.0.0', port=5000)